### ISSUE TITLE
Change h2 of show_browse

### ISSUE THREAD

**Issue by azirer** [justintadlock/breadcrumb-trail#23]
Following this https://github.com/justintadlock/breadcrumb-trail/pull/21 I 'm saying that `<h2>` tag should be avoided at that specific point.  I would use `<p>` instead. 
File inc/breadcrumbs.php line 169

https://html.spec.whatwg.org/multipage/semantics.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements

**Comment by justintadlock** [comment]
`<p>` would be incorrect for most themes.  A header tag is absolutely appropriate for a header, which is exactly what this is.  The use of `<h2>` specifically is because this is how core WP handles navigation headers by default.  I'd go as far as saying `<h1>` is the most appropriate, at least for HTML5-based themes.  

What I am open to is adding an argument (call it `browse_tag`) for allowing people to add their preferred tag.  That way, users can change it to match their theme's structure.

**Comment by azirer** [comment]
I believe that this is not header. A header could be something like `<h2>You are here: Home >> Products >> Some Specific Product</h2>` because it has a relative meaning to the content of the page. However  I wouldn't consider `<h2>You are here:</h2>` as a proper header, especially on SEO terms. Anyway I completely agree with you on `browse_tag` to let people do whatever they want with it.

**Comment by justintadlock** [comment]
Headers aren't required to be page-level headers.  `<nav>` is a sectioning element and can have its own header.

I'm not arguing over whether it should be a header though.  As the author, I say it's a header.  Therefore, it's a header. :)
